name: Pipeline
on:
  push:
    branches: [ "deploy/dev" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete husky
        run: npm pkg delete scripts.prepare
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  unit_tests:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete husky
        run: npm pkg delete scripts.prepare
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm run test
  build:
    needs: [unit_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: pustart/money-pie-api-dev:latest
